version: "3"
services:
  api-server:
    image: api-server
    ports:
      - "5000:5000"
    networks:
      - mean-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    networks:
      - mean-app
    volumes:
      - mongo-data:/data/db
networks:
  mean-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
